apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pythonapp_dep
  labels:
    app: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pyhonapp
    spec:
      containers:
      - name: pythonapp
        image: 998252513391.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service1
metadata:
  name: pyservice
spec:
  selector:
    app: pythonapp
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31200
